### ISSUE TITLE
Build.sh shell script giving error on macos

### ISSUE THREAD

**Issue by prashant3167** [sjp38/tpcds-mariadb#1]
I am using mac with m1 chip and getting the below error
`tpcds-mariadb % ./build.sh
~/Downloads/tpcds-mariadb/tpcds-kit/tools ~/Downloads/tpcds-mariadb
D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DYYDEBUG  -DOSX    -c -o mkheader.o mkheader.c
/bin/sh: -D_LARGEFILE_SOURCE: command not found
make: [mkheader.o] Error 127 (ignored)
D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DYYDEBUG  -DOSX   -o mkheader mkheader.o 
/bin/sh: -D_LARGEFILE_SOURCE: command not found
make: [mkheader] Error 127 (ignored)
./mkheader column_list.txt
make: ./mkheader: No such file or directory
make: *** [tables.h] Error 1
~/Downloads/tpcds-mariadb`

**Comment by sjp38** [comment]
Hi Prashant, thank you for opening this issue!  Unfortunately, this repo was developed on Ubuntu only, and I don't have mac :'(  It would be great if you could make and pull-request fix.
